version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
